create table annotations
(
    gtex_id    varchar(42),
    smatsscr   real,
    smcenter   varchar(10),
    smpthnts   text,
    smrin      real,
    smts       varchar(20),
    smtsd      varchar(45),
    smubrid    varchar(12),
    smtsisch   real,
    smtspax    real,
    smnabtch   varchar(40),
    smnabtcht  varchar(55),
    smnabtchd  date,
    smgebtch   varchar(35),
    smgebtchd  date,
    smgebtcht  varchar(40),
    smafrze    varchar(10),
    smgtc      varchar(20),
    sme2mprt   real,
    smchmprs   real,
    smntrart   real,
    smnumgps   integer,
    smmaprt    real,
    smexncrt   real,
    sm550nrm   integer,
    smgnsdtc   real,
    smunmprt   real,
    sm350nrm   integer,
    smrdlgth   real,
    smmncpb    integer,
    sme1mmrt   real,
    smsflgth   real,
    smestlbs   real,
    smmppd     real,
    smnterrt   real,
    smrrnanm   real,
    smrdttl    real,
    smvqcfl    real,
    smmncv     integer,
    smtrscpt   real,
    smmppdpr   real,
    smcglgth   integer,
    smgappct   integer,
    smunpdrd   real,
    smntrnrt   real,
    smmpunrt   real,
    smexpeff   real,
    smmppdun   real,
    sme2mmrt   real,
    sme2anti   real,
    smaltalg   real,
    sme2snse   real,
    smmflgth   real,
    sme1anti   real,
    smspltrd   real,
    smbsmmrt   real,
    sme1snse   real,
    sme1pcts   real,
    smrrnart   real,
    sme1mprt   real,
    smnum5cd   integer,
    smdpmprt   real,
    sme2pcts   real,
    cohort     varchar(20),
    sex        integer,
    age        integer,
    race       integer,
    ethncty    integer,
    hght       real,
    hghtu      varchar(5),
    wght       real,
    wghtu      varchar(5),
    bmi        real,
    incexc     boolean,
    trisch     varchar(25),
    trischd    real,
    trchstin   varchar(25),
    trchstind  real,
    trcclmp    varchar(25),
    trcclmpd   real,
    trorgns    text,
    tramp      varchar(25),
    trcrtmp    real,
    trcrtmpu   varchar(1),
    trcrtmpl   varchar(40),
    trtptref   varchar(25),
    trvntsr    varchar(25),
    trdnisch   real,
    dthprnint  varchar(30),
    dthptpref  varchar(25),
    dthatpsy   real,
    dthrfg     real,
    dthcert    real,
    dthvnt     real,
    dthfucod   text,
    dthhrdy    real,
    dthcod     text,
    dthfucoddu varchar(5),
    dthfucodd  real,
    dthcoddu   varchar(5),
    dthcodd    real,
    dthlucoddu varchar(5),
    dthlucodd  real,
    dthlucod   text,
    dthmnnr    varchar(15),
    dthrfgdu   varchar(5),
    dthrfgd    real,
    dthdtrmn   varchar(30),
    dthplce    varchar(40),
    dthvntdu   varchar(5),
    dthvntd    real,
    dthwtns    real,
    dthcls     real,
    dthtyp     real,
    dthcat     real,
    dthicd10   real,
    lbcmvtab   real,
    lbebvgab   real,
    lbebvmab   real,
    lbhbcabm   real,
    lbhbcabt   real,
    lbhbsab    real,
    lbhbsag    real,
    lbhcv1nt   real,
    lbhbhcvab  real,
    lbhiv1nt   real,
    lbhivab    real,
    lbhivo     real,
    lbprrvdrl  real,
    lbrpr      real,
    mhabnwbc   real,
    mhals      real,
    mhalzdmt   real,
    mhalzhmr   real,
    mharthts   real,
    mhascites  real,
    mhasthma   real,
    mhbctinf   real,
    mhblddnd   real,
    mhblddndr  text,
    mhbldocnt  real,
    mhbrnph    real,
    mhbrnwght  real,
    mhcancer5  real,
    mhcancerc  real,
    mhcancernm real,
    mhcllults  real,
    mhclrd     real,
    mhcocaine5 real,
    mhcopd     real,
    mhcoughu   real,
    mhcvd      real,
    mhdlysis   real,
    mhdmntia   real,
    mhdprssn   real,
    mhdrnksts  varchar(10),
    mhdrnktp   varchar(10),
    mhdrnknmb  real,
    mhdrnkprd  varchar(10),
    mhdrnkyrs  real,
    mhdrnkcmt  text,
    mhdtnd72h  real,
    mhencepha  real,
    mheuro5    real,
    mhflu      real,
    mhfnginf   real,
    mhfvru     real,
    mhgencmt   text,
    mhgnrr12m  real,
    mhhepbct   real,
    mhhepcct   real,
    mhheroin   real,
    mhhgh      real,
    mhhivct    real,
    mhhivnt    real,
    mhhmphlia  real,
    mhhmphliab real,
    mhhrtatt   real,
    mhhrtdis   real,
    mhhrtdisb  real,
    mhhtn      real,
    mhinflne   real,
    mhivdrg5   real,
    mhjakob    real,
    mhlapthu   real,
    mhlupus    real,
    mhlvrdis   real,
    mhmenina   real,
    mhms       real,
    mhmsxwma   real,
    mhmsxwmb   real,
    mhneph     real,
    mhnghtswt  real,
    mhnphys4w  real,
    mhnrtheur  real,
    mhopnwnd   real,
    mhoppinf   real,
    mhorgntp   real,
    mhostmylts real,
    mhpllabs   real,
    mhpnmiab   real,
    mhpnmnia   real,
    mhprcnp    real,
    mhprknsn   real,
    mhpsbldclt real,
    mhra       real,
    mhrbsanml  real,
    mhreyes    real,
    mhrnlflr   real,
    mhsars     real,
    mhschz     real,
    mhsclrdrm  real,
    mhsdrgabs  real,
    mhsepsis   real,
    mhsknspt   real,
    mhsmksts   varchar(10),
    mhsmktp    varchar(10),
    mhsmknmb   real,
    mhsmkprd   varchar(10),
    mhsmkyrs   real,
    mhsmkcmt   text,
    mhsmlpxct  real,
    mhsmlpxvc  real,
    mhsrc      varchar(15),
    mhsrcdss   real,
    mhsrghm    real,
    mhstd      real,
    mhstrdlt   real,
    mhsubabsa  real,
    mhsubabsb  real,
    mhsxmda    real,
    mhsxmdb    real,
    mhsyph12m  real,
    mhszrsu    real,
    mht1d      real,
    mht2d      real,
    mhtbhx     real,
    mhtempu    real,
    mhttcmt    text,
    mhttoo12m  real,
    mhttoonp   real,
    mhtxcexp   real,
    mhuk8096   real,
    mhuremia   real,
    mhwknssu   real,
    mhwnvct    real,
    mhwnvhx    real,
    mhwtlsua   real,
    mhwtlsub   real,
    dthseason  varchar(10),
    dthtime    time,
    tissue     varchar(40)
);

create table data_dictionary
(
    varname varchar(10),
    vardesc varchar(310),
    varmeta varchar(10),
    vartype varchar(25)
);

create table ensembl2symbol
(
    alias      varchar(32),
    ensembl_id varchar(22),
    symbol     varchar(25),
    entrez_id  integer
);

create table expression_correlation
(
    gene_a      varchar(15),
    gene_b      varchar(15),
    tissue      varchar(40),
    correlation real
);

create table gene_expression
(
    ensembl_id varchar(22),
    gtex_id    varchar(30),
    level      integer
);

create table metadata
(
    gtex_id varchar(30),
    tissue  varchar(40),
    varname varchar(10),
    value   text
);

create table metadata_data_records
(
    gtex_id varchar(42),
    varname varchar(10),
    value   text
);

create table metadata2expression
(
    varname        varchar(10),
    ensembl_id     varchar(25),
    tissue         varchar(40),
    test           varchar(20),
    test_statistic real,
    pvalue         double precision
);

create table metadata2metadata
(
    category_a     varchar(10),
    category_b     varchar(10),
    tissue         varchar(40),
    test           varchar(20),
    test_statistic real,
    pvalue         double precision
);

create table phenotype_data_records
(
    subject_id varchar(10),
    varname    varchar(10),
    value      text
);
