# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"

[dev.global.parameters]
region = "us-east-2"
stack_name = "dev-seahorse"
s3_bucket = "seahorse-sam-cli"
s3_prefix = "dev"
tags = "Environment=dev"
parameter_overrides = "Environment=dev"

[prod.global.parameters]
region = "us-east-2"
stack_name = "prod-seahorse"
s3_bucket = "seahorse-sam-cli"
s3_prefix = "prod"
tags = "Environment=prod"
parameter_overrides = "Environment=prod"
